2016-04-12 01:54:12,090 - streamparse.stdout - INFO - ('cache lookup failed for relation 17082\n',)
2016-04-12 01:54:12,090 - streamparse.stdout - INFO - cache lookup failed for relation 17082

2016-04-12 01:54:33,147 - streamparse.stdout - INFO - Errored out
2016-04-12 01:54:42,844 - streamparse.stdout - INFO - Errored out
2016-04-12 01:54:44,919 - streamparse.stdout - INFO - Errored out
2016-04-12 01:54:45,103 - streamparse.stdout - INFO - Errored out
2016-04-12 01:54:49,006 - streamparse.stdout - INFO - Errored out
2016-04-12 01:54:53,081 - streamparse.stdout - INFO - Errored out
2016-04-12 01:54:59,178 - streamparse.stdout - INFO - Errored out
2016-04-12 01:55:02,889 - streamparse.stdout - INFO - Errored out
2016-04-12 01:55:12,390 - streamparse.stdout - INFO - Errored out
2016-04-12 01:55:18,855 - streamparse.stdout - INFO - Errored out
2016-04-12 01:55:20,450 - streamparse.stdout - INFO - Errored out
2016-04-12 01:55:23,688 - streamparse.stdout - INFO - Errored out
2016-04-12 01:55:25,881 - streamparse.stdout - INFO - Errored out
2016-04-12 01:55:25,982 - streamparse.stdout - INFO - Errored out
2016-04-12 01:55:26,640 - streamparse.stdout - INFO - Errored out
2016-04-12 01:55:29,849 - streamparse.stdout - INFO - Errored out
2016-04-12 01:55:30,628 - streamparse.stdout - INFO - Errored out
2016-04-12 01:55:36,359 - streamparse.stdout - INFO - Errored out
2016-04-12 01:55:37,183 - streamparse.stdout - INFO - Errored out
2016-04-12 01:55:43,280 - streamparse.stdout - INFO - Errored out
2016-04-12 01:55:47,605 - streamparse.stdout - INFO - Errored out
2016-04-12 01:55:54,735 - streamparse.stdout - INFO - Errored out
2016-04-12 01:55:55,248 - streamparse.storm.component - ERROR - Received EOF while trying to read stdin from Storm, pipe appears to be broken, exiting.
2016-04-12 01:55:55,248 - streamparse.stdout - INFO - Errored out
2016-04-12 01:55:55,248 - streamparse.storm.component - ERROR - Received EOF while trying to read stdin from Storm, pipe appears to be broken, exiting.
2016-04-12 01:55:55,248 - streamparse.stdout - INFO - Errored out
2016-04-12 01:55:55,249 - streamparse.storm.component - ERROR - Received EOF while trying to read stdin from Storm, pipe appears to be broken, exiting.
2016-04-12 01:55:55,249 - streamparse.stdout - INFO - Errored out
2016-04-12 01:55:55,249 - streamparse.storm.component - ERROR - Received EOF while trying to read stdin from Storm, pipe appears to be broken, exiting.
2016-04-12 01:55:55,249 - streamparse.stdout - INFO - Errored out
2016-04-12 01:55:55,249 - streamparse.storm.component - ERROR - Received EOF while trying to read stdin from Storm, pipe appears to be broken, exiting.
2016-04-12 01:55:55,249 - streamparse.stdout - INFO - Errored out
2016-04-12 01:55:55,250 - streamparse.storm.component - ERROR - Received EOF while trying to read stdin from Storm, pipe appears to be broken, exiting.
2016-04-12 01:55:55,250 - streamparse.stdout - INFO - Errored out
2016-04-12 01:55:55,250 - streamparse.storm.component - ERROR - Received EOF while trying to read stdin from Storm, pipe appears to be broken, exiting.
2016-04-12 01:55:55,250 - streamparse.stdout - INFO - Errored out
2016-04-12 01:55:55,250 - streamparse.storm.component - ERROR - Received EOF while trying to read stdin from Storm, pipe appears to be broken, exiting.
2016-04-12 01:55:55,250 - streamparse.stdout - INFO - Errored out
2016-04-12 01:55:55,251 - streamparse.storm.component - ERROR - Received EOF while trying to read stdin from Storm, pipe appears to be broken, exiting.
2016-04-12 01:55:55,251 - streamparse.stdout - INFO - Errored out
2016-04-12 01:55:55,251 - streamparse.storm.component - ERROR - Received EOF while trying to read stdin from Storm, pipe appears to be broken, exiting.
2016-04-12 01:55:55,251 - streamparse.stdout - INFO - Errored out
2016-04-12 01:55:55,252 - streamparse.storm.component - ERROR - Exception in WordCounter.run()
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/streamparse/storm/component.py", line 489, in run
    self._run()
  File "/usr/lib/python2.7/site-packages/streamparse/storm/bolt.py", line 221, in _run
    self.ack(tup)
  File "/usr/lib/python2.7/site-packages/streamparse/storm/bolt.py", line 193, in ack
    self.send_message({'command': 'ack', 'id': tup_id})
  File "/usr/lib/python2.7/site-packages/streamparse/storm/component.py", line 368, in send_message
    self.output_stream.flush()
IOError: [Errno 32] Broken pipe
